# Generated by Django 5.0.3 on 2024-05-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_name',
        ),
    ]
