FROM node:20.9.0-alpine3.18

WORKDIR /usr/src/web/

COPY ./web/package.json /usr/src/web/package.json
COPY ./web/package-lock.json /usr/src/web/package-lock.json
RUN npm install

EXPOSE 3000

COPY ./web /usr/src/web