# Generated by Django 5.0.3 on 2024-04-14 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_event_name_alter_playerpoints_user'), ('api', '0003_playerscore_delete_playerpoints'), ('api', '0004_alter_playerscore_event_alter_playerscore_sumula_and_more'), ('api', '0005_alter_playertotalscore_user_alter_token_token_code'), ('api', '0006_alter_token_token_code'), ('api', '0007_alter_token_token_code'), ('api', '0008_alter_token_token_code'), ('api', '0009_alter_token_token_code'), ('api', '0010_alter_token_token_code'), ('api', '0011_alter_token_token_code'), ('api', '0012_alter_token_token_code')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_code', models.CharField(default='', max_length=8, unique=True)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='Sumula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='api.event')),
                ('referee', models.ManyToManyField(related_name='referee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sumula',
                'verbose_name_plural': 'Sumulas',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='api.token'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to='api.event')),
                ('sumula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to='api.sumula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlayerScore',
                'verbose_name_plural': 'PlayerScores',
            },
        ),
        migrations.CreateModel(
            name='PlayerTotalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_scores', to='api.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
