# Generated by Django 5.0.3 on 2024-05-18 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('active', models.BooleanField(default=True)),
                ('token_players', models.CharField(blank=True, default='', max_length=8, unique=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'permissions': [('add_sumula_event', 'Can add sumula'), ('change_sumula_event', 'Can change sumula'), ('view_sumula_event', 'Can view sumula'), ('delete_sumula_event', 'Can delete sumula'), ('add_player_event', 'Can add player'), ('change_player_event', 'Can change player'), ('view_player_event', 'Can view player'), ('delete_player_event', 'Can delete player'), ('add_player_score_event', 'Can add player_score'), ('change_player_score_event', 'Can change player_score'), ('view_player_score_event', 'Can view player_score'), ('delete_player_score_event', 'Can delete player_score')],
            },
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PlayerScore',
                'verbose_name_plural': 'PlayerScores',
            },
        ),
        migrations.CreateModel(
            name='Sumula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sumula',
                'verbose_name_plural': 'Sumulas',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_code', models.CharField(default='', max_length=8, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('social_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('registration_email', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.event')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
