# Generated by Django 5.0.3 on 2024-05-05 02:58

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_code', models.CharField(default='', max_length=8, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_score', models.PositiveSmallIntegerField(default=0)),
                ('registration_email', models.EmailField(max_length=254, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.event')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'unique_together': {('registration_email', 'event')},
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sumula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sumulas', to='api.event')),
                ('referee', models.ManyToManyField(blank=True, related_name='sumulas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sumula',
                'verbose_name_plural': 'Sumulas',
            },
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_scores', to='api.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.player')),
                ('sumula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sumula_scores', to='api.sumula')),
            ],
            options={
                'verbose_name': 'PlayerScore',
                'verbose_name_plural': 'PlayerScores',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='api.token'),
        ),
    ]
