# Generated by Django 5.0.3 on 2024-05-05 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.event'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='sumula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.sumula'),
        ),
        migrations.AlterField(
            model_name='sumula',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sumulas', to='api.event'),
        ),
    ]
