# Generated by Django 5.0.3 on 2024-05-18 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='token_players',
        ),
    ]
