# Generated by Django 5.0.3 on 2024-05-18 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_event_token_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='players_token',
            field=models.CharField(blank=True, default='', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='api.event'),
        ),
    ]
