# Generated by Django 5.0.3 on 2024-05-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('add_sumula', 'Can add event sumula'), ('change_sumula', 'Can change event sumula'), ('view_sumula', 'Can view event sumula'), ('delete_sumula', 'Can delete event sumula'), ('add_player', 'Can add event player'), ('change_player', 'Can change event player'), ('view_player', 'Can view event player'), ('delete_player', 'Can delete event player'), ('add_player_score', 'Can add event player_score'), ('change_player_score', 'Can change event player_score'), ('view_player_score', 'Can view event player_score'), ('delete_player_score', 'Can delete event player_score')], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
