# Generated by Django 5.0.3 on 2024-05-11 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('add_sumula_event', 'Can add sumula'), ('change_sumula_event', 'Can change sumula'), ('view_sumula_event', 'Can view sumula'), ('delete_sumula_event', 'Can delete sumula'), ('add_player_event', 'Can add player'), ('change_player_event', 'Can change player'), ('view_player_event', 'Can view player'), ('delete_player_event', 'Can delete player'), ('add_player_score_event', 'Can add player_score'), ('change_player_score_event', 'Can change player_score'), ('view_player_score_event', 'Can view player_score'), ('delete_player_score_event', 'Can delete player_score')], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
