# Generated by Django 5.0.3 on 2024-05-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_results_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_code',
            field=models.CharField(blank=True, default='', max_length=8, unique=True),
        ),
    ]
