# Generated by Django 5.0.3 on 2024-05-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_player_full_name_player_social_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='registration_email',
            field=models.EmailField(max_length=254),
        ),
    ]
