# Generated by Django 5.0.3 on 2024-05-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_staff_registration_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('registration_email', 'event')},
        ),
    ]
