# Generated by Django 5.0.3 on 2024-04-15 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0013_token_used'), ('api', '0014_alter_token_token_code'), ('api', '0015_alter_token_token_code'), ('api', '0016_alter_event_token_alter_sumula_event_and_more'), ('api', '0017_alter_playertotalscore_options')]

    dependencies = [
        ('api', '0001_squashed_0012_alter_token_token_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_code',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='api.token'),
        ),
        migrations.AlterField(
            model_name='sumula',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sumula', to='api.event'),
        ),
        migrations.AlterField(
            model_name='sumula',
            name='referee',
            field=models.ManyToManyField(related_name='sumula', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='playertotalscore',
            options={'verbose_name': 'PlayerTotalScore', 'verbose_name_plural': 'PlayerTotalScores'},
        ),
    ]
