# Generated by Django 5.0.3 on 2024-06-03 22:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_player_user_alter_staff_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('user', 'event')},
        ),
    ]
