# Generated by Django 5.0.3 on 2024-06-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_player_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumula',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
    ]
