# Generated by Django 5.0.3 on 2024-06-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_event_staff_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
