# Generated by Django 5.0.3 on 2024-06-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_event_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='players_token',
            field=models.CharField(blank=True, default='', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='staff_token',
            field=models.CharField(blank=True, default='', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_code',
            field=models.CharField(blank=True, default='', max_length=9, unique=True),
        ),
    ]
