# Generated by Django 5.0.3 on 2024-04-17 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_token_used_squashed_0017_alter_playertotalscore_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playertotalscore',
            unique_together={('user', 'event')},
        ),
    ]
