# Generated by Django 5.0.3 on 2024-06-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sumula_description'),
        ('api', '0017_alter_event_players_token_alter_event_staff_token_and_more'),
    ]

    operations = [
    ]
