# Generated by Django 5.0.3 on 2024-04-18 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_playertotalscore_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumula',
            name='referee',
            field=models.ManyToManyField(blank=True, null=True, related_name='sumula', to=settings.AUTH_USER_MODEL),
        ),
    ]
