# Generated by Django 5.0.3 on 2024-06-13 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_sumula_referee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerscore',
            name='sumula',
        ),
        migrations.AddField(
            model_name='player',
            name='is_imortal',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SumulaClassificatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='', max_length=256, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('referee', models.ManyToManyField(blank=True, related_name='sumula_classificatoria', to='api.staff')),
            ],
            options={
                'verbose_name': 'Sumula Classificatoria',
                'verbose_name_plural': 'Sumulas Classificatoria',
            },
        ),
        migrations.AddField(
            model_name='playerscore',
            name='sumula_classificatoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.sumulaclassificatoria'),
        ),
        migrations.CreateModel(
            name='SumulaImortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='', max_length=256, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('referee', models.ManyToManyField(blank=True, related_name='sumula_imortal', to='api.staff')),
            ],
            options={
                'verbose_name': 'Sumula Imortal',
                'verbose_name_plural': 'Sumulas Imortais',
            },
        ),
        migrations.AddField(
            model_name='playerscore',
            name='sumula_imortal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.sumulaimortal'),
        ),
        migrations.DeleteModel(
            name='Sumula',
        ),
    ]
