# Generated by Django 5.0.3 on 2024-04-18 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_sumula_referee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertotalscore',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_score', to='api.event'),
        ),
        migrations.AlterField(
            model_name='playertotalscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sumula',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sumulas', to='api.event'),
        ),
        migrations.AlterField(
            model_name='sumula',
            name='referee',
            field=models.ManyToManyField(blank=True, related_name='sumulas', to=settings.AUTH_USER_MODEL),
        ),
    ]
