# Generated by Django 5.0.3 on 2024-06-29 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_playerscore_sumula_player_is_imortal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.event'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.player'),
        ),
    ]
