# Generated by Django 5.0.3 on 2024-04-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_playerscore_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertotalscore',
            name='total_points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
