# Generated by Django 5.0.3 on 2024-06-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_event_players_token_remove_event_staff_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='registration_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
