# Generated by Django 5.0.3 on 2024-07-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_player_registration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
