# Generated by Django 5.0.3 on 2024-04-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_event_team_members_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumula',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
