# Generated by Django 5.0.3 on 2024-04-30 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_playerscore_event_alter_playerscore_sumula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='sumula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sumula'),
        ),
        migrations.AlterField(
            model_name='playerscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
