# Generated by Django 5.0.3 on 2024-05-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_playerscore_event_alter_playerscore_sumula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
