# Generated by Django 5.0.3 on 2024-08-11 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_sumulaclassificatoria_rounds_and_more'),
        ('api', '0033_alter_player_unique_together_and_more'),
    ]

    operations = [
    ]
