# Generated by Django 5.0.3 on 2024-10-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_merge_20240811_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumulaimortal',
            name='number',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sumulaclassificatoria',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sumulaimortal',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
