# Generated by Django 5.0.3 on 2024-10-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_sumulaimortal_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumulaclassificatoria',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='sumulaimortal',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
