# Generated by Django 5.1.1 on 2024-10-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_sumulas_generated',
            field=models.BooleanField(default=False),
        ),
    ]
